import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/header";
import Footer from "@/components/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <Header />
        <div className="min-h-screen m-10">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
